spring:
  profiles:
    active: @profiles.active@
  config:
    import:
      - optional:classpath:application-@profiles.active@-db.yml
      - optional:file:config/application-@profiles.active@-db.yml

#spring:
#  profiles:
#    active: ${spring.profiles.active:dev}
#  config:
#    import:
#      - optional:classpath:application-${spring.profiles.active:dev}-db.yml
#      - optional:file:config/application-${spring.profiles.active:dev}-db.yml

server:
  port: 8080
