spring:
  profiles:
    active: @profiles.active@
  config:
    import:
      - optional:classpath:application-@profiles.active@-db.yml
      - optional:classpath:application-@profiles.active@-task.yml
      - optional:file:config/application-db.yml
      - optional:file:config/application-task.yml

mybatis:
  mapper-locations:
    - classpath:net/p5w/dp/module/**/*.xml

server:
  port: 8080
